name: part2_jsonserializationrestapi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
# path: ^1.8.0
dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

  lints: ^4.0.0
  test: ^1.24.0
